# ======常规传感器（数值型）======
sensor:
  # 室外温度
  - platform: homeassistant
    name: xiamen temperature
    entity_id: sensor.xiamen_temperature
    id: xiamen_temp
    unit_of_measurement: "°C"
    on_value:
      then:
        - lvgl.label.update:
            id: outdoor_info
            text: !lambda |-
              return str_sprintf("室外：温度%.1f℃/湿度%.0f%%", x, id(xiamen_humi).state);

  # 室外湿度
  - platform: homeassistant
    name: xiamen humidity
    id: xiamen_humi
    entity_id: sensor.xiamen_humidity
    on_value:
      then:
        - lvgl.label.update:
            id: outdoor_info
            text: !lambda |-
              return str_sprintf("室外：温度%.1f℃/湿度%.0f%%", id(xiamen_temp).state, x);

  # 气压
  - platform: homeassistant
    name: xiamen pressure
    id: xiamen_pressure
    entity_id: sensor.xiamen_atmospheric_pressure
    unit_of_measurement: "hPa"
    on_value:
      then:
        - lvgl.label.update:
            id: air_info
            text: !lambda |-
              return str_sprintf("     气压%.1fhPa/PM2.5 %.0f", id(xiamen_pressure).state, x);
  # PM2.5
  - platform: homeassistant
    name: xiamen pm25
    id: xiamen_pm25
    entity_id: sensor.xiamen_pm25
    on_value:
      then:
        - lvgl.label.update:
            id: air_info
            text: !lambda |-
              return str_sprintf("     气压%.1fhPa/PM2.5 %.0f", id(xiamen_pm25).state, x);

  # 室内温度
  - platform: homeassistant
    name: xiaomi temperature
    entity_id: sensor.cleargras_cn_blt_3_u5c2qgggk400_dk1_temperature_p_2_1
    id: xiaomi_temp
    unit_of_measurement: "°C"
    on_value:
      then:
        - lvgl.label.update:
            id: indoor_info
            text: !lambda |-
              return str_sprintf("室内：%.1f℃/%.0f%%", x, id(xiaomi_humi).state);

  # 室内湿度
  - platform: homeassistant
    name: xiaomi humidity
    id: xiaomi_humi
    entity_id: sensor.cleargras_cn_blt_3_u5c2qgggk400_dk1_relative_humidity_p_2_2
    on_value:
      then:
        - lvgl.label.update:
            id: indoor_info
            text: !lambda |-
              return str_sprintf("室内：%.1f℃/%.0f%%", id(xiaomi_temp).state, x);

# ======二进制传感器（开/关状态）======
binary_sensor:
  # 传感器：小米插座1开关
  - platform: homeassistant
    id: chuangmi_socket1_status
    entity_id: switch.chuangmi_cn_125697630_m3_on_p_2_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: chuangmi_socket1_button
          state:
            checked: !lambda return x;

  # 传感器：小米插座2开关
  - platform: homeassistant
    id: chuangmi_socket2_status
    entity_id: switch.chuangmi_cn_125796823_m3_on_p_2_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: chuangmi_socket2_button
          state:
            checked: !lambda return x;

  # 传感器：小米插座3开关
  - platform: homeassistant
    id: chuangmi_socket3_status
    entity_id: switch.chuangmi_cn_125520813_m3_on_p_2_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: chuangmi_socket3_button
          state:
            checked: !lambda return x;

# 文本传感器
text_sensor:
  # 厦门天气预报
  - platform: homeassistant
    id: xiamen_weather
    entity_id: sensor.xiamen_forecast_minutely
    on_value:
      then:
        - lvgl.label.update:
            id: weather_alert_text
            text: !lambda |-
              return "预警: " + x;