esp32:
  variant: esp32
  flash_size: 4MB
  framework:
    type: esp-idf

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  name_add_mac_suffix: true

ota:
  platform: esphome

api:

logger:

psram:

# 屏幕背光控制 (GPIO47)
# - frequency: 150Hz PWM 频率（足够高以避免闪烁）
# - min_power: 最低亮度级别（1% — 防止完全熄灭）
# - zero_means_zero: 当设为 0 时，背光完全关闭
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO26
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

# 屏幕背光配置
light:
  - platform: monochromatic
    name: Backlight
    id: backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s
    internal: true

# SPI总线
spi:
  - id: lcd_spi
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12

# 触摸屏 (xpt2046)
touchscreen:
  - platform: xpt2046
    id: tft_touch
    spi_id: lcd_spi
    cs_pin: 33
    interrupt_pin: 32
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860


# 显示屏(ILI9341)
display:
  - platform: mipi_spi
    id: tft_display
    model: ILI9341
    spi_id: lcd_spi
    invert_colors: false
    data_rate: 40MHz
    cs_pin: 15
    dc_pin: 4
    reset_pin:
      number: 25
      inverted: true
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 320
      height: 240
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false